### ISSUE TITLE
Internal Server Error/Server error is thrown when dataset set is created with USGIN Yes and Author,metadata information is given

### ISSUE THREAD

**Issue by sbalmuri-rei** [ngds/ckanext-ngds#595] opened 2014-12-19 19:47 UTC
Internal Server Error/Server error is thrown when dataset set is created with USGIN Yes and Author,metadata information is given.

![servererror](https://cloud.githubusercontent.com/assets/8029135/5510228/ebdf5642-878d-11e4-8905-1d76ab041b7c.png)

**Comment by ccaudill** [comment] 2015-02-13 17:15
@sbalmuri-rei Could you clarify on how this error might be reproduced?

**Comment by ccaudill** [comment] 2015-02-13 17:25
I understand - when publishing the data. I successfully added a record with the author and metadata information. Looks like this have been fixed in new build.

**Closed by ccaudill** 2015-02-13 17:25 UTC
