### ISSUE TITLE
Cannot recreate a deleted harvest source

### ISSUE THREAD

**Issue by mattmackenzie** [ngds/ckanext-ngds#411] opened 2014-03-20 18:04 UTC
I deleted all harvest sources and tried to re-add. They are gone from the UI, but they are obviously retained elsewhere.
![screen shot 2014-03-20 at 3 02 48 pm](https://f.cloud.github.com/assets/653087/2475669/03ae68e6-b05a-11e3-837f-17dc14817da6.png)
![screen shot 2014-03-20 at 3 03 10 pm](https://f.cloud.github.com/assets/653087/2475671/06d3efa0-b05a-11e3-82e9-6e58db44dae8.png)

**Comment by ccaudill** [comment] 2015-03-05 18:17
This is a function of stock CKAN; it does not hard delete anything. So, the solution given is to run a script nightly to hard delete anything that the admin chose to delete. @FuhuXia  This will work, but the problem is that the user is going to be pretty annoyed if they have to wait until the next day to publish the same record that they just deleted. Is there any way for an admin to force this kind of action right away, then couple that with a script that runs nightly to hard delete?

**Comment by dan-olaru-reisys** [comment] 2015-03-16 17:42
@ccaudill the fix that @FuhuXia suggested is to just run cron every 5 minutes, or if need be, we can run it every minute. The cron job will be part of the rpm, let me know if this will work for you.

**Comment by ccaudill** [comment] 2015-03-17 04:03
I think even running it every 5 minutes is a good solution, if this won't significantly influence the speed of the rest of the functions. Perhaps in this case, the user could get a message upon deleting a resource that those changes could take as long as 5 minutes to propagate. Much better than it not being deleted at all.

**Closed** 2015-03-30 19:17 UTC
Labels: NGDS-v1.0, priority.Major, sys.Harvest

**Comment by dan-olaru-reisys** [comment] 2015-03-30 19:18
this should be working as expected: http://uat-ngds.reisys.com/
